ENH Prepare theme for adoption as a supported module
silverstripe/startup-theme pull request #9
Opened 2024-12-27 00:11 UTC by GuySartorelli

## Issue
- https://github.com/silverstripe/startup-theme/issues/7

2025-01-22 23:59 UTC, GuySartorelli commented on images/block1-image.webp
Unused file

2025-01-22 23:59 UTC, GuySartorelli commented on images/chevron--down--white.svg
Unused file

2025-01-22 23:59 UTC, GuySartorelli commented on css/accordion.css
Adds functional CSS to correspond with the accordion.js
Previously, CSS was applied only to narrow-scoped navigation-related CSS classes and was not reusable.

This both allows for additional accordions to be added using this JS (e.g. in an accordion elemental block) _and_ allows the same functionality to be used for both mobile nav and desktop nav.

2025-01-22 23:59 UTC, GuySartorelli commented on css/base.css
> +}
Form validation messages - test using userforms.

2025-01-22 23:59 UTC, GuySartorelli commented on css/header.css
Changes here include:
- Expand link to fill the whole tappable space in mobile nav (used to only be the text itself - tapping slightly to the side would do nothing)
- Remove functional CSS that is now in the accordion styling
- Remove on-hover expanding of desktop menu in favour of reusing existing accordion functionality
- Update some styling for hover states and layout as appropriate to accomodate the above

2025-01-26 23:49 UTC, emteknetnz requested changes
I'm a bit confused by this PR, it seems like there's a bunch of changes made from what the Pikachu's originally did and was presumably signed off by the design team? Or have I misunderstood what this PR's doing?

Based on the notes in the original description it seemed like this PR should only be changing the composer name?

2025-01-26 23:54 UTC, GuySartorelli commented
The work the Pikachus did was primarily for the purposes of the demo. This PR brings the theme up to a standard we'd be comfortable with for the default supported installer theme. These changes come after these acceptance criteria:

- The theme gets a review from a "does this do what a default theme needs to do" pov
- The theme gets a lightweight code quality review

In my view, the theme as it was before this PR is not of an appropriate standard, as it is missing some important styling (e.g. table styles, margin below paragraphs, some hover styles), is missing template variables that should be included (e.g. `$ElementalArea`), is missing some accessibility improvements (see changes to navigation), and isn't easily built on top of (e.g. `$resourceURL` instead of `$themedResourceURL`).

The changes I've made in this PR bring it to the minimum standard I'm comfortable with including as the default supported theme.

2025-01-27 22:25 UTC, emteknetnz requested changes
### TinyMCE formatting doesn't work:

- Bullet list
- Numbered list
- Align center
- Align right
- Justiry
- Italic displays as underline

### Content block vertical spacing

In a content block context, along with the TinyMCE formatting points above, vertical spacing is also lacking when using the out of the box content block

### "Home" in the navigation

In the breadcrumb the page "Home" is (incorrectly IMO) acting as the root page where pages like "About us" are treated as child pages, rather than sibling pages.   I don't think we should show "Home" in the breadcrumb. You can simply click on the top-left logo to get back to the home page which is intuitive.  Also just seeing the word "Home" looks weird, you don't see this on most websites.

Also I don't think "Home" should show in the top/accordian nav, as again you can just click the logo to go to the home page

2025-01-27 22:36 UTC, emteknetnz requested changes
### Userform vertical spacing

In a userform context, along with the TinyMCE formatting points above, vertical spacing is lacking

### Deeply nested pages don't work in accordian

In the accordian nav, sub-sub pages do not show

### Excessive vertical space in breadcrumb

There is excessive vertical space between the breadcrumb and the header

2025-01-27 22:48 UTC, GuySartorelli commented
Discussed offline:
- Vertical space for userform should be between each field holder
- For nested pages, just add child pages into the sidebar

2025-01-28 03:50 UTC, GuySartorelli commented
Turns out most of the typography styling was in the `wysiwyg.css` file for some reason - which _explicitly only_ applied to the WYSIWYG field in the CMS and not to the frontend.

I have now moved that out into the frontend CSS (which is _also_ included in the WYSIWYG field in the CMS).

> Italic displays as underline

This is the one thing I cannot reproduce.

2025-01-28 03:54 UTC, GuySartorelli commented
> Content block vertical spacing

Assuming you mean space between blocks, this seems fine to me? Note that "Okie doke" is the end of one block, and "some block" is the start of the next one.
![image](https://github.com/user-attachments/assets/226e0c19-7079-43f1-b822-55e1532ccfe6)

2025-01-28 03:57 UTC, GuySartorelli commented
> Also I don't think "Home" should show in the top/accordian nav, as again you can just click the logo to go to the home page

That can be configured in the CMS by setting "show in menus" to false. Because of this I won't change how the template handles it unless you insist.

2025-01-29 02:53 UTC, GuySartorelli commented on css/block.css
Styles here weren't being used

2025-01-29 02:53 UTC, GuySartorelli commented on css/hero.css
Styles here weren't being used

2025-01-29 02:53 UTC, GuySartorelli commented on css/section.css
Styles here weren't being used

2025-01-29 02:54 UTC, GuySartorelli commented on css/transitions.css
Moved to base to reduce number of network calls required to load all css since this is just a single declaration

2025-01-29 02:54 UTC, GuySartorelli commented on css/wysiwyg.css
Moved relevant styles to typography so they apply to frontend as well

2025-01-29 02:55 UTC, GuySartorelli commented on css/base.css
> -    width: 100%;
Was overriding the `height` and `width` attributes from WYSIWYG

2025-01-29 02:55 UTC, GuySartorelli commented on css/form.css
Form styles adapted from simple theme

2025-01-29 21:54 UTC, emteknetnz requested changes
Opened desktop "accordian" should close if click anywhere on page that's not the accordian

Set h1 margin-bottom: 2.4rem;

Set h2,h3,h4,h5,h6 margin-top: 2.4rem;

The right hand nav that shows on subpages
- parent page link should be underlined to show that it's a link
- on mobile, needs a thin grey horizontal line above it to denote that it's a nav section as moves from the right and will display underneath page content. Should remove the thin grey line below the parent page link on mobile view.

2025-01-29 21:59 UTC, GuySartorelli commented
> Opened desktop "accordian" should close if click anywhere on page that's not the accordian

That's not how accordions tend to work - but I'll agree to doing this in the narrow scope of the menu. I'll add code for this that is specific to the menu or to some optional attribute that other accordions can choose to exclude.

> parent page link should be underlined to show that it's a link

Oh, I didn't know that was a link lol. Will do.

2025-01-30 01:14 UTC, GuySartorelli commented
Converted the `rem` margins to `em` so that they scale with font size.

2025-01-30 01:53 UTC, GuySartorelli commented
Made the requested changes - also noted the JS was missing semicolons so I've plopped those in.

2025-01-30 21:47 UTC, emteknetnz approved these changes

2025-01-30 21:47 UTC, merged